language: haxe
haxe:
  - stable      # the latest stable release defined in https://haxe.org/download/list/
hxml:  
  - buildtests.hxml 
  - build.hxml
after_script:
  - node "./sUTLHaxeJS/sUTLTests.js" && ./scripts/pushbuild.sh