language: haxe
haxe:
  - stable      # the latest stable release defined in https://haxe.org/download/list/
hxml:  
  - buildtests.hxml 
  - build.hxml
after_script:
  - node "./sUTLHaxeJS/sUTLTests.js"
# && ./scripts/pushbuild.sh
deploy:
  provider: pages
  local_dir: sUTLHaxeJS
  repo: emlynoregan/sUTLHaxeJS
  target_branch: dev
  skip_cleanup: true
  github_token: $TOKEN # Set in travis-ci.org dashboard
  on:
    branch: dev
